# Generated by Django 2.2.5 on 2020-01-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todoitem_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='due_date',
            new_name='deadline',
        ),
    ]
